### ISSUE TITLE
Substructure search

### ISSUE THREAD

**Issue by mattholc** [matteoferla/Python_SmallWorld_API#5]
It looks like it's only possible to do the SmallWorld search type through this python API, while the SmallWorld Server also supports other modes, such as substructure and superstructure. Is there a way to access those through this API?

**Comment by matteoferla** [comment]
I never spent time analysing the calls for those, but as far as I can tell the calls are the same, the difference is the settings as seen in the sliders in advanced settings.

Vanilla:

    https://sw.docking.org/search/submit?smi=C14%3DNC%3DCC%3DC1C%3DC(C3%3DC(C2CCCCC2)C%3DCC%3DC3)C%3DC4&db=for-sale.smi.anon&dist=4&sdist=12&tdn=6&tup=6&rdn=6&rup=2&ldn=2&lup=2&maj=6&min=6&sub=6&scores=Atom%20Alignment,ECFP4,Daylight

Substructure

     https://sw.docking.org/search/submit?smi=C14%3DNC%3DCC%3DC1C%3DC(C3%3DC(C2CCCCC2)C%3DCC%3DC3)C%3DC4&db=for-sale.smi.anon&dist=4&sdist=12&tdn=0&tup=6&rdn=0&rup=2&ldn=0&lup=0&maj=0&min=0&sub=6&scores=Atom%20Alignment,ECFP4,Daylight

Superstructure

    https://sw.docking.org/search/submit?smi=C14%3DNC%3DCC%3DC1C%3DC(C3%3DC(C2CCCCC2)C%3DCC%3DC3)C%3DC4&db=for-sale.smi.anon&dist=4&sdist=12&tdn=6&tup=0&rdn=6&rup=0&ldn=0&lup=0&maj=0&min=0&sub=6&scores=Atom%20Alignment,ECFP4,Daylight
 
Murcko

    https://sw.docking.org/search/submit?smi=C14%3DNC%3DCC%3DC1C%3DC(C3%3DC(C2CCCCC2)C%3DCC%3DC3)C%3DC4&db=for-sale.smi.anon&dist=4&sdist=12&tdn=6&tup=6&rdn=0&rup=0&ldn=0&lup=0&maj=6&min=6&sub=6&scores=Atom%20Alignment,ECFP4,Daylight

However https://arthor.docking.org/ can do those and has a friendlier API ([Pythonic usage example](https://github.com/matteoferla/Arthorian-Quest/blob/main/arthorian_quest/query.py)), but does not give a `atomMap` back!
